apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: olymahmudmugdho/cne-ecommerce-ui:083219e5a51db0334ba5d1ba571b2d9eb1cf02c5
          ports:
            - containerPort: 4173
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
