apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: olymahmudmugdho/inventory-service:cc96aa70a033fe25f2b63632914508fab0637b24
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
